version: "3.3"
services:
  app:
    build:
      args:
        user: ubuntu
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: devops
    container_name: devops-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - devops

  nginx:
    image: nginx:1.17-alpine
    container_name: devops-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - devops

  jenkins:
      image: jenkins/jenkins:lts
      privileged: true
      user: root
      ports:
        - 8080:8080
        - 50000:50000
      container_name: jenkins
      volumes:
        - ./docker-compose/jenkins/jenkins_configuration:/var/jenkins_home
        - ./var/run/docker.sock:/var/run/docker.sock
      networks:
        - devops

  agent:
      image: jenkins/ssh-agent:jdk11
      privileged: true
      user: root
      container_name: agent
      expose:
        - 22
      environment:
        - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzCxdTBkE88je+qo+V9a9MS7tcaWrZgl3hsH1G+z0RwYuD4DlQ/gAhpZIiEtfS2tgaW7w14n8BFRK1agw2KO9Y86LW9Yf6zHPKt/6Djbz4Tb53oTYH62RuF6dXnhqyK/aXEhz63LRsIWz0e2xPm2qdeVWzqcsS94IQBDBi0X0V7HiYGc5+GQRzXBtXlL4IH92ckWsWkZyBEiElnNQ3HbJ3O+Qyk89FWXpfNSIWruvNVhXQ6a6rdhPM9JX6/YuybB3n7zZ/9ID1/Fpb3CJYFw+OL2agPYDwqtzTQyba3/5eY1hvHLD2SvIk7yMQzjI9cFcs5TxImCN8VW5+8pfWVE

networks:
  devops:
    driver: bridge
